name = "SpatialHashTables"
uuid = "894afd4e-5c6f-4d1a-a294-873acbd0e95c"
authors = ["Steffen Plunder <steffen.plunder@web.de> and contributors"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
