name = "SpatialHashTables"
uuid = "894afd4e-5c6f-4d1a-a294-873acbd0e95c"
authors = ["Steffen Plunder <steffen.plunder@web.de> and contributors"]
version = "0.2.1"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Adapt = "3"
StaticArrays = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["Test","LinearAlgebra"]
